export { PostgresEventStore } from "./src/eventStore/PostgresEventStore.js"
export type { PostgresEventStoreOptions } from "./src/eventStore/PostgresEventStore.js"
export type { LockStrategy } from "./src/eventStore/lockStrategy.js"
export { advisoryLocks, rowLocks } from "./src/eventStore/lockStrategy.js"
export { runHandler } from "./src/eventHandling/runHandler.js"
export type { HandlerRunnerOptions, RunningHandler } from "./src/eventHandling/runHandler.js"
export { createProcessor } from "./src/eventHandling/processor.js"
export type { ProcessorOptions, RunningProcessor } from "./src/eventHandling/processor.js"
export { createConsumer } from "./src/eventHandling/consumer.js"
export type { ConsumerOptions, ConsumerProcessorConfig, RunningConsumer } from "./src/eventHandling/consumer.js"
export type { StartPosition } from "./src/eventHandling/startPositions.js"
export { waitUntilProcessed } from "./src/eventHandling/waitUntilProcessed.js"
export { WaitTimeoutError } from "./src/eventHandling/WaitTimeoutError.js"
export { ensureHandlersInstalled } from "./src/eventHandling/ensureHandlersInstalled.js"

export type { Projection, ProjectionContext } from "./src/projections/projection.js"
export { rawSqlProjection } from "./src/projections/rawSqlProjection.js"
export type { RawSqlProjectionOptions } from "./src/projections/rawSqlProjection.js"
export { projectionToProcessor } from "./src/projections/projectionAdapter.js"
export type { ProjectionProcessorOptions } from "./src/projections/projectionAdapter.js"
export { ProjectionSpec } from "./src/projections/projectionSpec.js"
export { pongoProjection } from "./src/projections/pongo/pongoProjection.js"
export type { PongoProjectionOptions, PongoProjectionContext } from "./src/projections/pongo/pongoProjection.js"
export { pongoDocumentProjection } from "./src/projections/pongo/pongoDocumentProjection.js"
export type { PongoDocumentProjectionOptions } from "./src/projections/pongo/pongoDocumentProjection.js"
